### ISSUE TITLE
Spam cast dot

### ISSUE THREAD

**Issue by sp3sh** [fiskee/DMWC-Warlock#1]
Downloaded a fresh copy of DMWC and Warlock but it seems to constantly spam one curse until oom then rinse repeat. I am unable to ascertain which exactly but i think it is agony or corruption.

**Comment by sp3sh** [comment]
Further testing, it started with siphon life so i disabled it then it started spamming another curse. As i disabled that it spammed immolate. Unsure why it wont detect the curse on target,

Update thought i found the issue but i did not

**Comment by sp3sh** [comment]
Ok so its not the rotation - there is two combat disable functions in GMR
/run GMRCombat(false) and /run GMR_Combat(false)
turn both off if you have this issue

**Comment by fiskee** [comment]
Tried to replicate but can't, try disabling other addons, if you have, especially if you use GMR, please try without this and see if issue is there still

**Comment by sp3sh** [comment]
Will try and report back.

**Comment by sp3sh** [comment]
Confirmed when GMR not used it works perfect.
